Feature/IO_735_caching
elizaveta-seleznyova-idf/movie_and_stars pull request #11
Opened 2022-10-28 14:12 UTC by elizaveta-seleznyova-idf

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf approved these changes

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/data/lib/database/database_provider.dart
> +       ${MovieDBModelField.movieType} $textType,
I think to have primary key is a good practice. Purpose of primary key is to identify the uniqueness of a row, also it will help to get your data access faster.

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/data/lib/database/database_provider.dart
> +       FOREIGN KEY (movieId) REFERENCES Movies(movieIdTmdb) ON DELETE CASCADE
A FOREIGN KEY is a field (or collection of fields) in one table, that refers to the [PRIMARY KEY](https://www.w3schools.com/sql/sql_primarykey.asp) in another table.

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/data/lib/repository/cast_database_local_repository.dart
> +  }
up to u, u can create named constructor in PeolpeAndImagesModel, to create instance from map

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/data/lib/repository/movie_database_local_repository.dart
> +    movieIdList.addAll(await getMoviesIdsFromCache(movieType));
final List<int> movieIdList = await getMoviesIdsFromCache(movieType);

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/data/lib/repository/preference_local_repository.dart
> +  Future<bool> saveDate(String date) async {
from name I can't understand in which case it should to return true or false

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/data/lib/repository/preference_local_repository.dart
> +      if (convertedDateResponse.isAfter(convertedSavedData)) {
if here u trying to know is convertedDateResponse is next day after convertedSavedData, then it wrong way. Cuz method "after" compares milisecondsSinceEpoch and do not compares days

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/data/lib/repository/preference_local_repository.dart
> +      await sharedPreferences.setString(
up to u, but on my opinion, is the more preferred way to save date is to save it DateTime.fromMillisecondsSinceEpoch value

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/domain/lib/model/movie_db_model.dart
> +class MovieDBModelField {
private contractor

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/domain/lib/model/people_and_images_model.dart
> +class CastDBModelField {
-\\-

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/domain/lib/model/movie_db_model.dart
> +class MovieDBModelField {
private contractor

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/domain/lib/use_case/get_movies_use_case.dart
> +    final GetDataResponse response = type == MovieType.trending
before make call to api or fetching from cache u should to know last api call date, then compare with current date and decide to use cached movies or do api call.

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/domain/lib/use_case/get_movies_use_case.dart
> +        int itemCount = 50;
final or const

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/domain/lib/use_case/get_movies_use_case.dart
> +      });
think about mapper

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/domain/lib/use_case/get_movies_use_case.dart
> +          addToList(responseWithItem);
no need in addToList method just make a method with return responseWithItem for example:

final List<MovieResponse> jsonMovies = await fetchMoviesFromApi(MovieType type, int itemsCount);

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/domain/lib/use_case/get_movies_use_case.dart
> +          addToList(responseWithItem);
additionally,  separate logic in this class, by methods please

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/domain/lib/use_case/get_people_use_case.dart
>          await _traktRepository.getCast(movieId: params);
same, why do u make api call before checking cache?

2022-11-03 16:51 UTC, vladimir-hodaryonok-idf commented on packages/domain/lib/use_case/get_people_use_case.dart
> +    }
same, separate logic due methods please

2022-11-04 08:45 UTC, egor-slatvinskiy-idf approved these changes

2022-11-09 17:00 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/database/database_provider.dart
> +       ${MovieDBModelField.movieType} $textType,
Agreed that using primary key is a good practice, but here we don't need it, because we have 3 ids for every movie and which of them use to set primary key?

2022-11-09 17:00 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/repository/cast_database_local_repository.dart
> +  }
I like my way, but I'll think about it

2022-11-09 17:00 UTC, elizaveta-seleznyova-idf commented on packages/domain/lib/use_case/get_people_use_case.dart
>          await _traktRepository.getCast(movieId: params);
I need to check date from response

2022-11-09 17:00 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/database/database_provider.dart
> +       FOREIGN KEY (movieId) REFERENCES Movies(movieIdTmdb) ON DELETE CASCADE
okay, but if I will need to make another table where I need key movieIdSlug. I need to make it primary too?

2022-11-09 17:00 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/repository/preference_local_repository.dart
> +  Future<bool> saveDate(String date) async {
I don't know better short and understandable name for this function

2022-11-09 17:00 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/repository/preference_local_repository.dart
> +      await sharedPreferences.setString(
I use function for compare 2 dates where I need save and use date like this.

2022-11-09 17:00 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/repository/preference_local_repository.dart
> +      if (convertedDateResponse.isAfter(convertedSavedData)) {
okay, maybe u r right. I use another construction for compare 2 dates

2022-11-09 17:00 UTC, elizaveta-seleznyova-idf commented on packages/domain/lib/use_case/get_movies_use_case.dart
> +    final GetDataResponse response = type == MovieType.trending
I need to make api call for compare two dates. And what I need to do if I don't have any saved date?

2022-11-10 09:26 UTC, yuliya-klescheva-idf approved these changes

2022-11-10 09:26 UTC, yuliya-klescheva-idf commented on packages/data/lib/repository/cast_database_local_repository.dart
> +  CastDBLocalRepositoryImpl({required this.db});
add const

2022-11-11 14:06 UTC, alexei-kruk-idf requested changes

2022-11-11 14:06 UTC, alexei-kruk-idf commented on packages/data/lib/repository/cast_database_local_repository.dart
> +          ),
you should use batch

2022-11-11 14:06 UTC, alexei-kruk-idf commented on packages/data/lib/repository/movie_database_local_repository.dart
> +    }
-//-

2022-11-11 14:06 UTC, alexei-kruk-idf commented on packages/data/lib/repository/preference_local_repository.dart
> +  }
move to mapper or Extension

2022-11-15 13:09 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/repository/cast_database_local_repository.dart
> +          ),
added

2022-11-15 13:09 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/repository/movie_database_local_repository.dart
> +    }
-//-

2022-11-15 13:19 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/repository/preference_local_repository.dart
> +  }
moved

2022-11-15 13:24 UTC, alexei-kruk-idf approved these changes

2022-11-16 09:22 UTC, sergei-mikhailovskii-idf requested changes

2022-11-16 09:22 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/database/database_provider.dart
> +    return _database!;
```suggestion
    if (_database == null) _database = await _initDB(dbName);
    return _database!;
```

the same, but more compact

2022-11-16 09:22 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/database/database_provider.dart
> +       ${MovieDBModelField.movieType} $textType,
use any of them

2022-11-16 09:22 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/database/database_provider.dart
> +       FOREIGN KEY (movieId) REFERENCES Movies(movieIdTmdb) ON DELETE CASCADE
agree with Vova. link it with PK

2022-11-16 09:22 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/cast_database_local_repository.dart
> +        batch.insert(
use `insert or ignore`. it will allow us to avoid manual check if cast record is exist

2022-11-16 09:22 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/cast_database_local_repository.dart
> +  }
better to move it into separate mapper

2022-11-16 09:22 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/cast_database_local_repository.dart
> +  Future<int> deleteCast(
u shouldn't delete the cast manually. it should be deleted by cascade

2022-11-16 09:22 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/movie_database_local_repository.dart
> +    final List<int> movieIdList = [];
logic connected to the ids comparison should be moved into usecase

2022-11-16 09:22 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/preference_local_repository.dart
> +  final MovieDBLocalRepository movieDBLocalRepository;
don't inject repo into the repo

2022-11-16 09:22 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/preference_local_repository.dart
> +  Future<bool> saveDate(String date) async {
save the date into the separate table, let's have consistent flow

2022-11-16 09:22 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/preference_local_repository.dart
> +    final convertedDateResponse = convertStringToDate(date);
this should be in usecase

2022-11-16 09:22 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/preference_local_repository.dart
> +        final stringDate = convertedDateResponse.toString();
move the checks into usecase too

2022-11-16 09:22 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/use_case/get_movies_use_case.dart
> +    final GetDataResponse response = type == MovieType.trending
u shouldn't make an API call before the check. if there's no saved date - execute the API call. if u have the saved date - compare them

2022-11-17 13:08 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/database/database_provider.dart
> +    return _database!;
okay

2022-11-17 13:08 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/database/database_provider.dart
> +       FOREIGN KEY (movieId) REFERENCES Movies(movieIdTmdb) ON DELETE CASCADE
okay

2022-11-17 13:08 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/repository/cast_database_local_repository.dart
> +        batch.insert(
<img width="665" alt="Screenshot 2022-11-17 at 15 07 50" src="https://user-images.githubusercontent.com/111364147/202442138-845e4fdc-2426-4d68-9792-3c99528e8746.png">

2022-11-17 13:08 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/repository/cast_database_local_repository.dart
> +  }
okay :(

2022-11-17 14:39 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/repository/cast_database_local_repository.dart
> +  Future<int> deleteCast(
delete this function

2022-11-18 08:09 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/database/database_provider.dart
> +      CREATE TABLE IF NOT EXISTS $castTableName (
here u also need a PK

2022-11-18 08:09 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/cast_database_local_repository.dart
> +        batch.insert(
use it in raw insert

2022-11-18 12:49 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/database/database_provider.dart
> +      CREATE TABLE IF NOT EXISTS $castTableName (
added

2022-11-18 12:49 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/repository/cast_database_local_repository.dart
> +        batch.insert(
made it

2022-11-18 12:49 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/repository/preference_local_repository.dart
> +  final MovieDBLocalRepository movieDBLocalRepository;
deleted

2022-11-18 12:49 UTC, elizaveta-seleznyova-idf commented on packages/data/lib/repository/preference_local_repository.dart
> +  Future<bool> saveDate(String date) async {
created new table for date

2022-11-24 06:14 UTC, closed without merging