add share_plugin
elizaveta-seleznyova-idf/movie_and_stars pull request #7
Opened 2022-10-11 15:50 UTC by elizaveta-seleznyova-idf

2022-10-11 19:20 UTC, vladimir-hodaryonok-idf approved these changes
to many redundant files

2022-10-11 19:20 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/l10n/intl_be.arb
> +  "share": "Глядзі, які я знайшол фільм! \\n\\n https://www.themoviedb.org/movie/{movieId}?language=ru",
знайшоу (у краткая) =)

2022-10-11 19:20 UTC, vladimir-hodaryonok-idf commented on ios/Podfile
> +# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
hmm .gitignore? and think about other files

2022-10-11 19:20 UTC, vladimir-hodaryonok-idf commented on packages/presentation/lib/screen/movie_details/details_screen.dart
> +                                  final message = movie?.ids?.tmdb ?? 0;
naming. message? not id?

2022-10-11 19:20 UTC, vladimir-hodaryonok-idf commented on packages/share_plugin/example/test/widget_test.dart
> +import 'package:flutter/material.dart';
on my opinion, all your example project should be deleted from star_movie

2022-10-11 19:20 UTC, vladimir-hodaryonok-idf commented on packages/share_plugin/lib/share_plugin_method_channel.dart
> +        {'message': message},
if u share only a string it redundant to use map. U can just pass string to the native platform

2022-10-12 07:13 UTC, egor-slatvinskiy-idf approved these changes
You have too much superfluous in PR. Before calling further, clean the project of unnecessary files, comments, etc.

2022-10-12 13:16 UTC, elizaveta-seleznyova-idf commented on packages/presentation/lib/l10n/intl_be.arb
> +  "share": "Глядзі, які я знайшол фільм! \\n\\n https://www.themoviedb.org/movie/{movieId}?language=ru",
бес папутаў

2022-10-13 13:01 UTC, elizaveta-seleznyova-idf commented on packages/presentation/lib/screen/movie_details/details_screen.dart
> +                                  final message = movie?.ids?.tmdb ?? 0;
changed

2022-10-13 13:01 UTC, elizaveta-seleznyova-idf commented on packages/share_plugin/example/test/widget_test.dart
> +import 'package:flutter/material.dart';
It makes sense, but I didn't delete it because of thinking that maybe I'll publish this package to Pubspec.yaml

2022-10-14 13:41 UTC, alexei-kruk-idf approved these changes

2022-10-14 13:41 UTC, alexei-kruk-idf commented on packages/presentation/lib/app/app_bottom_navigation_bar.dart
> +import 'package:flutter/material.dart';import 'package:flutter_svg/flutter_svg.dart';
new line

2022-10-14 14:01 UTC, yuliya-klescheva-idf approved these changes

2022-10-17 08:07 UTC, sergei-mikhailovskii-idf requested changes

2022-10-17 08:07 UTC, sergei-mikhailovskii-idf commented on lib/firebase_options.dart
> +// File generated by FlutterFire CLI.
discussed it - remove the file if u don't need it

2022-10-17 08:07 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/login/widgets/login_registration_button.dart
> +        onPressed: blocFunction,
naming - `blocFunction` doesn't say about anything

2022-10-17 08:07 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/movie_details/details_bloc.dart
> +    required BuildContext context,
https://stackoverflow.com/a/58505881/10597533

2022-10-17 08:07 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/movie_details/widgets/details_body.dart
> +    const double rating = Dimens.size5;
define separate const for maxRating. don't use dimen

2022-10-17 08:07 UTC, sergei-mikhailovskii-idf commented on packages/share_plugin/android/src/main/kotlin/com/elizaveta/share_plugin/SharePlugin.kt
> +        val sharingIntent = Intent.createChooser(sendIntent, "Movie Sharing")
pass Movie Sharing as an argument to the plugin. in the same way u do it with message. since plugin can be used in any other project, not only in Movie Sharing

2022-10-17 08:07 UTC, sergei-mikhailovskii-idf commented on packages/share_plugin/example/ios/Podfile.lock
> +PODS:
delete the file

2022-10-17 08:07 UTC, sergei-mikhailovskii-idf commented on packages/share_plugin/ios/Classes/SwiftSharePlugin.swift
> +              let message = arguments["message"] as! String
throw an exception with message `"It's required to pass the message param to the plugin"`. u can do it via `guard` construction (https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html)

2022-10-18 14:15 UTC, elizaveta-seleznyova-idf commented on lib/firebase_options.dart
> +// File generated by FlutterFire CLI.
deleted

2022-10-18 14:15 UTC, elizaveta-seleznyova-idf commented on packages/presentation/lib/screen/login/widgets/login_registration_button.dart
> +        onPressed: blocFunction,
changed

2022-10-18 14:15 UTC, elizaveta-seleznyova-idf commented on packages/presentation/lib/screen/movie_details/details_bloc.dart
> +    required BuildContext context,
fixed

2022-10-18 14:15 UTC, elizaveta-seleznyova-idf commented on packages/presentation/lib/screen/movie_details/widgets/details_body.dart
> +    const double rating = Dimens.size5;
changed

2022-10-18 20:12 UTC, sergei-mikhailovskii-idf approved these changes

2022-10-18 20:12 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/movie_details/widgets/details_body.dart
> +    const double rating = 5;
```suggestion
    const double maxRating = 5;
```

2022-10-19 06:01 UTC, elizaveta-seleznyova-idf commented on packages/presentation/lib/screen/movie_details/widgets/details_body.dart
> +    const double rating = 5;
resolved

2022-10-19 06:02 UTC, merged